services:
    app.email_displayer:
        class: App\EmailDisplayer
        arguments:
            - '@connection.config.full_connection_factory_basic'
            - '@mail.search_criteria.collection_builder_basic'
            - '@mail.repository.basic'