services:
    twig.file.loader:
        class: Twig_Loader_Filesystem
        arguments: ['%twig.templates.dir%']

    twig.engine:
        class: Twig_Environment
        arguments: ['@twig.file.loader', '%twig.engine.options%']

    app.email_displayer.non_strict_factory_method:
        class: App\NonStrictFactoryMethodEmailDisplayer
        arguments:
            - '%imap.gmail.account_one.userName%'
            - '%imap.gmail.account_one.password%'
            - '@connection.factory.basic'
            - '@mail.search_criteria.collection_builder_basic'
            - '@mail.repository.basic'
            - '@twig.engine'

    app.email_displayer_with_builders:
        class: App\BuildersEmailDisplayer
        arguments:
            - '%imap.gmail.account_one.userName%'
            - '%imap.gmail.account_one.password%'
            - '@connection.factory.basic'
            - '@connection.config.builder_parameter_bag'
            - '@connection.config.mail_box_builder_parameter_bag'
            - '@connection.config.mail_box_flag_collection_builder_basic'
            - '@connection.config.option_collection_builder_basic'
            - '@mail.search_criteria.collection_builder_basic'
            - '@mail.repository.basic'
            - '@twig.engine'

    app.email_displayer.pre_defined_connection:
        class: App\PreDefinedConnectionFactoryEmailDisplayer
        arguments:
            - '@app.connection_factory.pre_defined_connection_gmail_account_one'
            - '@mail.search_criteria.collection_builder_basic'
            - '@mail.repository.basic'
            - '@twig.engine'

    app.email_displayer.connection_injection:
        class: App\ConnectionInjectedEmailDisplayer
        arguments:
            - '@connection.gmail.account_one'
            - '@mail.search_criteria.collection_builder_basic'
            - '@mail.repository.basic'
            - '@twig.engine'

    app.connection_factory.pre_defined_connection_gmail_account_one:
        class: App\Connection\PreDefinedGmailConnectionFactory
        arguments:
            - '%imap.gmail.account_one.userName%'
            - '%imap.gmail.account_one.password%'
            - '%imap.gmail.account_one.mailBox%'
            - '@connection.factory.basic'
            - '@connection.config.builder_parameter_bag'
            - '@connection.config.mail_box_builder_parameter_bag'
            - '@connection.config.mail_box_flag_collection_builder_basic'
            - '@connection.config.option_collection_builder_basic'

    app.connection_factory.pre_defined_connection_gmail_account_two:
        class: App\Connection\PreDefinedGmailConnectionFactory
        arguments:
            - '%imap.gmail.account_two.userName%'
            - '%imap.gmail.account_two.password%'
            - '%imap.gmail.account_two.mailBox%'
            - '@connection.factory.basic'
            - '@connection.config.builder_parameter_bag'
            - '@connection.config.mail_box_builder_parameter_bag'
            - '@connection.config.mail_box_flag_collection_builder_basic'
            - '@connection.config.option_collection_builder_basic'

    connection.gmail.account_one:
        class: PhpImap\Connection\Basic\BasicConnection
        factory: ['@connection.factory.basic', createConnectionNonStrict]
        arguments:
            - '%imap.gmail.account_one.userName%'
            - '%imap.gmail.account_one.password%'
            - '%imap.gmail.account_one.connectionRetries%'
            - '%imap.gmail.account_one.mailBox%'
            - '%imap.gmail.account_one.remoteSystemName%'
            - '%imap.gmail.account_one.port%'
            - '%imap.gmail.account_one.flags%'
            - '%imap.gmail.account_one.otions%'
            - '%imap.gmail.account_one.params%'
