services:
    app.email_displayer:
        class: App\EmailDisplayer
        arguments:
            - '@connection.connection.factory_basic'
            - '@mail.search_criteria.collection_builder_basic'
            - '@mail.repository.basic'
            - '@twig.engine'

    twig.file.loader:
        class: Twig_Loader_Filesystem
        arguments: ['%twig.templates.dir%']

    twig.engine:
        class: Twig_Environment
        arguments: ['@twig.file.loader', '%twig.engine.options%']